### ISSUE TITLE
Basic authentication for online serve

### ISSUE THREAD

**Issue by ozgurOdun** [msoedov/hacker-slides#14]
Hi Alex, 
maybe a basic authentication procedure can be written to index and edit pages so the hacker-slides can be served to internet behind a web server. I will try to implement this in my spare time.

**Comment by msoedov** [comment]
That's sound like a  reasonable feature. Any pull request will be welcomed :) I will see if I get time to work on this.  Thank you for suggestion @ozgurOdun

**Comment by msoedov** [comment]
@ozgurOdun just made a new release with basic auth middleware :)

**Comment by ozgurOdun** [comment]
i will be testing today and let you know if any bugs or improvments. Thanks a lot :)

**Comment by msoedov** [comment]
We can work on bug fixes in a separate issue
