### ISSUE TITLE
Display local images?

### ISSUE THREAD

**Issue by heyarne** [msoedov/hacker-slides#23]
When trying to drag images into the `slides` folder and try to display them, I get a `200` response but the body is a fully rendered html file instead of my image. Does the server serve static files from somewhere? Ideally I could just drop in the image into `slides` and reference it like `![alt-text](./img.png)`, is that possible?

**Comment by msoedov** [comment]
Yeah definitely! It can serve static files from slides/images/*.png. It would also nice to have some UI functionality for file but that could be not really trivial to implement.

**Comment by heyarne** [comment]
I agree. Drag and drop uploading like github would be amazing but I guess this would be non-trivial to implement. I will see if I find the time to look at this. Is there a specific reason for the `images` prefix? I tried putting it into the same folder and it didn't work so I was a bit confused.

**Comment by msoedov** [comment]
>  Is there a specific reason for the `images` prefix
Just for sake of example, it could be named differently
>  I tried putting it into the same folder and it didn't work so I was a bit confused.
I have not look to the code, but it's need to go to some of static files folder

**Comment by heyarne** [comment]
I can't really get images to work unfortunately… What exactly is the path? I've got a `dummy.png` in `slides/images`. `http://localhost:8080/slides/images/dummy.png` gives me a 404. Any advice?

**Comment by msoedov** [comment]
Hi @heyarne the image needs to be served from a static files router https://github.com/msoedov/hacker-slides/blob/master/main.go#L33
You can try to add this line 
```
r.Static("/images", "./slides/images")
```

**Comment by heyarne** [comment]
Ah okay I see. I just placed it into `./slides` and saw that everything weird `imgname.png.md` files got created. Will take a look later!

**Comment by nmaas87** [comment]
Any progress on that issue? Thank you very much :)

**Comment by nmaas87** [comment]
It works :).
I added the option as well as documentation, if you want to merge :)?

**Comment by msoedov** [comment]
Thanks @nmaas87  man! It can be closed now
