### ISSUE TITLE
Start with markdown file in `/slides`

### ISSUE THREAD

**Issue by heyarne** [msoedov/hacker-slides#24]
A feature request: If there's markdown files in the `/slides` folder, start with the first one in there. This would allow me to always start the docker container via `docker run --rm -v $(pwd)/slides:/app/slides` and I wouldn't have to manually clean them up manually.

I see however how this might be confusing (e.g. which file does it take?). Thoughts on this?

**Comment by msoedov** [comment]
So do you suggest to start with the most recently changed `md` file?  I thing that make a lot of sense

**Comment by heyarne** [comment]
Hm. Actually I thought a bit more about it and maybe it would be nice like this, but it's very much tailored to **my** needs:

* One Instance is for one slideset
* The slides are persisted in `slides/slides.md`
* Either slides are taken from that file or, if no file is present, `slides.md` is created with the getting started slides
* For a new slideset start a new instance

I think this would work well because the docker image is very small. You get file system persistance, and you can just restart the server in the same folder to have the same state again. Also it would make the app even less complex.

**Comment by msoedov** [comment]
I can't say for sure  what is the most common use case. I would not break the existing workflow. I think just by modifying the logic to start with the most recent modified file would fit to both use cases .

**Comment by heyarne** [comment]
Is there a possibility at the moment to have multiple slideshows? I saw that on each start a random markdown file is generated and I also saw the `stash` feature. I don’t quite understand it though and I don’t know how to open old slideshows except for copy-pasting.

**Comment by msoedov** [comment]
> Is there a possibility at the moment to have multiple slideshows? 

The current file name is stored in the session, so you can not simultaneously **edit**  multiple slides rom the same browser.
However you can present simultaneously any number of slides (I have not tried that)

>  I don’t quite understand it though and I don’t know how to open old slideshows except for copy-pasting.

There is supposed to be a button with a quirk UI to open stashed slides.  Last time I look it was there 2 month ago :)

**Comment by msoedov** [comment]
#25

**Comment by msoedov** [comment]
Great ! I will close this issue than. Thank you for your feedback :)
