### ISSUE TITLE
using '--' for separate vertical slides

### ISSUE THREAD

**Issue by servusoft** [msoedov/hacker-slides#28]
The separator '--'  not works for vertical slides, probaly not implemented,
https://revealjs.com/#/2

Its possible to implement?

**Comment by msoedov** [comment]
Its, I don't have a time to add this feature. I will just leave to up for grabs

**Comment by servusoft** [comment]
do you update the docker repository?

**Comment by msoedov** [comment]
No yet, I will make a new minor release as well :)

**Comment by msoedov** [comment]
Done

**Comment by servusoft** [comment]
No problem, I look later. 

I think, the ACE editor may updated , then the old revealjs can be removed.

**Comment by msoedov** [comment]
Good call #31! It's definitely needs to be clean up

**Comment by servusoft** [comment]
great, now it runs directly from docker repo!

well, the ACE editor there is olny in the old version.
I think, one of the minifed versions can be used., like 
https://github.com/ajaxorg/ace-builds/tree/master/src-min
