### ISSUE TITLE
[Feature request] Export to pdf

### ISSUE THREAD

**Issue by abrugh** [msoedov/hacker-slides#8]
Probably a tall order but being able to save the rendered slides as a pdf file would be stupendous.

**Comment by abrugh** [comment]
This is apparently easy-ish to accomplish, within chrome at least, adding `?print-pdf` to the end of the presentation view brings up a view that can then be printed, although you have to select 'Background Graphics' to get anything to appear.

**Comment by msoedov** [comment]
@abrugh Good call, I will make a patch this week.

**Comment by msoedov** [comment]
@abrugh you can pull the recent changes via git or docker, lemme know if you will have any issues

**Comment by abrugh** [comment]
Great! one question i have is, how can i change the template/style, if i had black text on white background printing wouldn't require background images?

**Comment by msoedov** [comment]
> how can i change the template/style, 
There is a separate issue #10

**Comment by msoedov** [comment]
I guess it can be closed now
